### ISSUE TITLE
Volunteer is not Registering and new Object id for same Volunteer!

### ISSUE THREAD

**Issue by ritwickbhargav80** [dsckiet/uddeshhya_backend#2]
Please correct it! @shrutiagrwal 

### Attachments:

**See object id:**
![Screenshot from 2019-06-28 12-14-11](https://user-images.githubusercontent.com/47817908/60322938-603cf180-999e-11e9-829e-5e2301545e27.png)

**See object id here too:**
![Screenshot from 2019-06-28 12-14-40](https://user-images.githubusercontent.com/47817908/60322945-6337e200-999e-11e9-91b3-0fdaf944db9b.png)

> (PS:- it should be same)

No entry in my DB:
![Screenshot from 2019-06-28 12-16-36](https://user-images.githubusercontent.com/47817908/60323072-a7c37d80-999e-11e9-8e3d-c2740eb15f3a.png)

> (PS:- It should get registered)

Thanks!

**Comment by ritwickbhargav80** [comment]
Actually, **req.body.email** in **routes/volunteer_form.js** is undefined and other attributes too..

**Comment by goelaakash79** [comment]
**resolved**
